/********** PLANTS ACTION TYPES *************** */

export const FETCH_PLANETS_STARTED = "FETCH_PLANETS_STARTED";
export const FETCH_PLANETS_END = "FETCH_PLANETS_END";
export const FETCH_PLANETS_FAILURE = "FETCH_PLANETS_FAILURE";
export const FETCH_PLANETS_SUCCESS = "FETCH_PLANETS_SUCCESS";

export const FETCH_STARSHIPS_STARTED = "FETCH_STARSHIPS_STARTED";
export const FETCH_STARSHIPS_END = "FETCH_STARSHIPS_END";
export const FETCH_STARSHIPS_FAILURE = "FETCH_STARSHIPS_FAILURE";
export const FETCH_STARSHIPS_SUCCESS = "FETCH_STARSHIPS_SUCCESS";